# Введение в машинное обучение. Часть 1

# Задания

**Задача 1.**

Даны четыре действительных числа: x1, y1, x2, y2. Напишите функцию distance(x1, y1, x2, y2), вычисляющая евклидово расстояние ( https://ru.wikipedia.org/wiki/%D0%95%D0%B2%D0%BA%D0%BB%D0%B8%D0%B4%D0%BE%D0%B2%D0%B0_%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D0%BA%D0%B0 ) между точкой (x1,y1) и (x2,y2).

In [10]:
def distance(x1, y1, x2, y2):
    return ((x1 - x2) ** 2 + (y1 - y2) ** 2) ** 0.5

print(distance(1,1,2,2))

1.4142135623730951


**Задача 2.**

Написать функцию season(month), принимающую 1 аргумент — номер месяца (от 1 до 12), которая присваивает глобальной переменной s время года, которому этот месяц принадлежит (зима, весна, лето или осень).

In [11]:
s= "winter"
def season(month):
    global s
    if month < 3:
        s = "winter"
    elif month < 6:
        s = "autumm"
    elif month < 9:
        s = "summer"
    elif month < 12:
        s = "spring"
    else:
        s = "winter"
    return None

for i in range(1,13):
    season(i)
    print(s)
    


winter
winter
autumm
autumm
autumm
summer
summer
summer
spring
spring
spring
winter


**Задача 3.**

Написать функцию is_prime, принимающую 1 аргумент — число от 0 до 1000, и возвращающую True, если оно простое, и False - иначе.

In [12]:
def is_prime(num):
    is_prime = True
    for i in range(2, num // 2 + 1): # нет смысла проверять числа > num // 2 + 1
        if num % i == 0:
            is_prime = False
            break
    return is_prime
for i in range(20):
    print(i, '-', is_prime(i))

0 - True
1 - True
2 - True
3 - True
4 - False
5 - True
6 - False
7 - True
8 - False
9 - False
10 - False
11 - True
12 - False
13 - True
14 - False
15 - False
16 - False
17 - True
18 - False
19 - True


**Задача 4.**

Написать функцию reverse_list(lst), которая принимает в качестве аргумента список и возвращаем его в перевернутом виде.

Например,
- исходный список:  8, 1, 0, 4
- полученный список: 4, 0, 1, 8

Использовать встроенные функции Python нельзя. 

In [13]:
def reverse_list(lst):
    reversed_lst = []
    for i in range(-1, -len(lst) - 1, -1): # используем отрицательную индексацию
        reversed_lst.append(lst[i])
    return reversed_lst
old_list = [1,2,3,4,5,6]
new_list = reverse_list(old_list)
print(new_list)

[6, 5, 4, 3, 2, 1]


**Задача 5.**

Распечатайте с 4 по 8 символ фразы "Привет мир!" приведенные к верхнему регистру.

In [14]:
txt = "Привет мир!"
print(txt[3:8].upper()) # используем срезы и встроенную функцию upper

ВЕТ М


**Задача 6.**

Напишите код, который все элементы массива x с нечетными индексами переставит в обратном порядке.

Т.е. если x = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], то код должен получать [0, 9, 2, 7, 4, 5, 6, 3, 8, 1]

In [15]:
def reverse_list_new(lst):
    reversed_lst = []
    for i in range(len(lst)):
        if i % 2 == 0:
            reversed_lst.append(lst[i])
        else:
            reversed_lst.append(lst[-i])
    return reversed_lst
old_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
new_list = reverse_list_new(old_list)
print(new_list)

[0, 9, 2, 7, 4, 5, 6, 3, 8, 1]


**Задача 7.**

Напишите цикл, который выводит все числа от 0 до 500, делящиеся на 7, если в них есть цифра 8.

In [16]:
for i in range(501):
    if i % 7 == 0 and '8' in str(i):
        print(i)

28
84
98
168
182
189
238
280
287
308
378
385
448
483


**Задача 8.**

На вход функция more_than_five(lst) получает список из целых чисел. 
Результатом работы функции должен стать новый список, в котором содержатся только те числа, которые больше 10 по модулю.

In [17]:
def more_than_five(lst):
    new_lst = [num for num in lst if abs(num) > 10]
    return new_lst
print(more_than_five([9,-11,12,100,-123, 2,3, 4]))

[-11, 12, 100, -123]


# Дополнительный материал для желающих

[Нескучный туториал по numpy](https://habr.com/ru/post/469355/)

# Задания

**Задача 1.**

Создать матрицу размером `10х10` с 0 внутри, и 1 на границах. Например для `3х3`.

```
1 1 1
1 0 1
1 1 1
```

In [18]:
import numpy as np
#size = int(input())
size = 10
mtrx = np.ones(shape=(size, size))
mtrx[1:size - 1, 1:size - 1] = np.zeros(shape=(size - 2, size - 2))
print(mtrx)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [19]:
arr = np.array([1,4,3,4,5,4,4])

arr.ndim

















1

**Задача 2.**

Создать 5x5 матрицу с 1,2,3,4 над диагональю. Все остальные элементы - 0.

In [20]:
mtrx = np.diag(np.arange(1, 5), k=1)
print(mtrx)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


**Задача 3.**

Создайте случайную матрицу и вычтите из каждой строки среднее.

In [21]:
mtrx = np.random.randn(5,5)
print(mtrx)
mtrx = mtrx.T - np.mean(mtrx[:, :5], axis=1)
print(mtrx)


[[ 0.81560561  0.33941165  0.83633566  0.7312451   0.10889849]
 [ 0.0527448   1.36933547 -1.39042727 -1.05795008 -0.37898735]
 [ 0.93798661  0.69589339 -0.78754325 -0.76185621  1.9975696 ]
 [-0.19575663 -1.13556905 -1.29207318  0.5487195   0.13811766]
 [-1.00738541 -0.96924521 -0.95131407 -0.16603253 -4.1042082 ]]
[[ 0.24930631  0.33380169  0.52157658  0.19155571  0.43225167]
 [-0.22688765  1.65039235  0.27948337 -0.74825671  0.47039188]
 [ 0.27003636 -1.10937038 -1.20395327 -0.90476084  0.48832301]
 [ 0.1649458  -0.7768932  -1.17826624  0.93603184  1.27360456]
 [-0.45740082 -0.09793046  1.58115957  0.52543    -2.66457112]]


**Задача 4.**

Написать функцию, принимающую на вход массив и меняющую знак у элементов, значения которых между 3 и 8. Протестировать на нескольких заданных вами массивах.

In [22]:
def inverse_arr(arr: np.ndarray[float]) -> np.ndarray[float]:
    """ Принимает на вход массив и меняет знак у элементов, значения которых между 3 и 8 """

    arr[(3 < arr) & (arr <= 8)] *= -1
    return arr
arr = np.random.randint(9,size=10)
print(arr)
print(inverse_arr(arr))

[4 1 8 1 7 1 4 4 1 1]
[-4  1 -8  1 -7  1 -4 -4  1  1]


**Задача 4.**

Написать функцию, принимающую на вход массив и вычитающую среднее из каждой строки в матрице. Протестировать на нескольких заданных вами примерах.

**Задача 5.**

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением.

In [23]:
arr = np.array([1,2,3,4,5])
nz = 3
arr1 = np.zeros(len(arr) + (len(arr)-1)*(nz))
arr1[::nz+1] = arr
print(arr1)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


**Задача 6.**


Написать функцию, принимающую на вход матрицу MxN и меняющую 2 любые строки в матрице. Протестировать на нескольких заданных вами примерах.

In [24]:
mtrx = np.arange(25).reshape(5,5)
mtrx[[1,0]] = mtrx[[0,1]]
mtrx

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**Задача 7.**


Написать функцию, принимающую на вход одномерный массив и возвращающую наиболее частое значение в массиве и частоту его встречи. Протестировать на нескольких заданных вами примерах.

In [25]:
arr = np.random.randint(5, size=100)
number = np.bincount(arr).argmax()
print(number)
print(np.bincount(arr)[number])


1
24


**Задача 8.** 

Написать функцию, принимающую на вход  массив 16x16 и считающую сумму по блокам 4x4. Протестировать на нескольких заданных вами примерах.

In [26]:
def block_summ(mtrx: np.ndarray) -> np.ndarray:
    """Принимает на вход  массив 16x16 и считает сумму по блокам 4x4"""
    k = 4
    S = np.add.reduceat(np.add.reduceat(mtrx, np.arange(0, mtrx.shape[0], k), axis=0), np.arange(0, mtrx.shape[1], k), axis=1)
    return S


print(block_summ(np.ones(shape=(16,16))))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


**Задача 9.**

Написать функцию, принимающую на вход матрицу и возвращающую n наибольших значений в массиве. n вводится с клавиатуры. Протестировать на нескольких заданных вами примерах.

In [27]:
def find_largest(mtrx: np.ndarray, n: int) -> np.ndarray:
    return mtrx[np.argpartition(-mtrx,n)[:n]]

print(find_largest(np.arange(10, ), 5))


[5 9 8 7 6]


**Задача 10.**

Написать функцию, принимающую на вход 10x3 матрица и находящую строки из неравных значений (например [2,2,3]). Протестировать на нескольких заданных вами примерах.

In [28]:
def not_equel(mtrx: np.ndarray) -> np.ndarray:
    E = np.logical_and.reduce(mtrx[:,1:] == mtrx[:,:-1], axis=1)
    return mtrx[~E]

print(not_equel(np.random.randint(3,size=(10,3))))

[[2 1 0]
 [1 2 0]
 [0 1 0]
 [1 0 2]
 [0 0 1]
 [0 2 2]
 [0 2 1]
 [2 0 0]
 [2 1 1]
 [2 0 1]]


**Задача 11.**

Написать функцию, принимающую на вход двумерный массив и находящую все различные строки. Протестировать на нескольких заданных вами примерах.

In [29]:
def different_rows(mtrx: np.ndarray) -> np.ndarray:
    T = np.ascontiguousarray(mtrx).view(np.dtype((np.void, mtrx.dtype.itemsize * mtrx.shape[1])))
    _, idx = np.unique(T, return_index=True)
    return mtrx[idx]

print(different_rows(np.random.randint(0, 2, (6,3))))


[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]]


**Задача 12.**

Написать функцию, принимающую на вход два вектора одинакого размера и считающую расстояние между векторами. Протестировать на нескольких заданных вами примерах.

In [30]:
def vec_dist(vec1: np.ndarray, vec2:np.ndarray) -> float:
    distance = np.sqrt(np.dot(vec1-vec2, vec1-vec2))
    return distance
vec1 = np.array((0, 0, 0))
vec2 = np.array((3, 3, 3))
print(vec_dist(vec1, vec2))

5.196152422706632


**Задача 13.**

Написать функцию, принимающую на вход два вектора одинакого размера и находящую косинус угла между векторами. Протестировать на нескольких заданных вами примерах.

In [31]:
def vec_dist(vec1: np.ndarray, vec2:np.ndarray) -> float:
    cos = np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))
    return cos
vec1 = np.array((1, 1, 0))
vec2 = np.array((0, 0, 3))
print(vec_dist(vec2, vec1))

0.0


**Задача 14.**

Написать функцию, принимающую на вход вектор A содержит float числа как больше, так и меньше нуля.

Функция должна округлить их до целых и результат записать в глобальную переменную Z. Округление должно быть "от нуля", т.е.:

- положительные числа округляем всегда вверх до целого
- отрицательные числа округляем всегда вниз до целого
- 0 остаётся 0

 Протестировать на нескольких заданных вами примерах.


**Задача 15.**

Написать функцию, принимающую на вход 2 вектора целых чисел A и B.

Функция должна находить числа, встречающиеся в обоих векторах и добавлять их по возрастанию в глобальную переменную - вектор Z.

*Если пересечений нет, то вектор Z будет пустым*.

 Протестировать на нескольких заданных вами примерах.

**Задача 16.**

    Написать функцию, принимающую на вход вектор и возвращающую максимальный элемент в векторе среди элементов, перед которыми стоит 0. 

Например для:

`x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])`

Ответ:
5

In [32]:
x = np.array([7, 0, 8, 11, 0, 4])
zero = x==0
print(x[1:][zero[:-1]].max())

8


**Задача 17.**

Написать функцию, принимающую на вход матрицу 5х3 и считающую длину каждого вектора в матрице (строка) и ищущую самый длинный вектор, вернуть его координаты и длину.

Как выглядит матрица:

```   
     | x | y | z |
     | 1 | 2 | 3 |
     | 3 | 4 | 1 |
     | ...       |
```